### ISSUE TITLE
Get on it

### ISSUE THREAD

**Issue by briandfoy** [briandfoy/big_bs_javascript_repo#4]
Tick tock, pitter patter

**Comment by Alhadis** [comment]
😉 You may find it easier to use [Linguist](https://github.com/github/linguist) for language detection:

~~~console
$ github-linguist js/ASMcvVltFrBvCB.js
js/ASMcvVltFrBvCB.js: 155 lines (155 sloc)
  type:      Text
  mime type: application/javascript
  language:  JavaScript

$ github-linguist --breakdown /path/to/briandfoy/big_bs_javascript_repo
99.90%  2317926    JavaScript
0.10%   2369       Perl
0.00%   43         Makefile

Makefile:
Makefile

Perl:
commit.pl
gen_js.pl

JavaScript:
js/ADTkEuqcxVs.js
js/ASMcvVltFrBvCB.js
js/ATxbiZUenIOBc.js
⋮
~~~

Details on how it works [can be found here](https://github.com/github/linguist/blob/master/docs/how-linguist-works.md). Basically, there's no "fuzzy logic" involved in analysing languages unless more than one language shares an extension (`.pl` could be a Perl or Prolog file, for example).

So if your intent was to confuse Linguist with obfuscated JavaScript code, it won't work because there's [only one language registered with the `.js` extension](https://github.com/github/linguist/blob/7efa7b3380ad0221c499f9ef1ca84c4dfcc0b299/lib/linguist/languages.yml#L2803). 😉

**Comment by briandfoy** [comment]
Wasn't thinking about Linguist at all. I know I can fool GitHub, but I'm thinking about the extra-GitHub services that look at repos.
